name = "discord-aad"
main = "src/worker.ts"
compatibility_date = "2023-06-28"

[vars]
AAD_EMAIL_REGEX = "^[a-z]{2}[0-9]{6}[dmp]@student.etf.bg.ac.rs$"
DISCORD_PLATFORM_NAME = "ETF student"

[[kv_namespaces]]
binding = "DISCORD_AAD"
id = "946ea8da2ef543439bfc4d7e188042a4"
